Setupfolders takes global flag, moved from main to commands.
gmisail/fontman-client pull request #23
Opened 2022-10-17 15:08 UTC by meowox

2022-10-17 15:43 UTC, meowox commented
This also resolves #8. I forgot to mention in 06f4381b82aad2d374d70d138b5d8cfe65587772 that SetupFolders now sets up the .config/fontman/ folder as well.

2022-10-18 00:37 UTC, gmisail requested changes
Everything looks good, just some minor variable name changes.

2022-10-18 00:37 UTC, gmisail commented on cmd/fontman/commands/install.go
> +	var ex_style string
I think this should be `exStyle` or `excludeStyle` just to maintain consistency.

2022-10-18 00:37 UTC, gmisail commented on cmd/fontman/commands/uninstall.go
> +	var ex_style string
Same thing as above, I think we should stick with camelCase if possible (I prefer pascal_case, but Go likes camelCase 🤷‍♂️)

2022-10-18 20:11 UTC, merged